# MIT No Attribution
#
# Copyright 2026 Eric Cornelissen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

name: Audit
on:
  pull_request:
    paths:
      - .github/workflows/audit-dev.yml
      - .ndmrc
      - .nsprc
      - package-lock.json
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  deprecations:
    name: Deprecations
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Audit for deprecations
        run: npm run audit:deprecations
  vulnerabilities:
    name: Vulnerabilities
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Audit for vulnerabilities
        run: npm run audit:vulnerabilities
      - name: Bump vulnerable dependencies
        if: failure() # && github.event_name == 'schedule'
        run: npm run audit:vulnerabilities:fix
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.1.1
        if: failure() # && github.event_name == 'schedule'
        with:
          title: Bump vulnerable dependencies
          body: |
            _This Pull Request was created automatically based on at least one
            known vulnerability detected in CI._
          labels: dependencies
          add-paths: package.json, package-lock.json
          branch: bump-vulnerable-dependencies
          commit-message: Bump vulnerable dependencies with `npm audit fix`
