name: Check
on:
  pull_request: ~
  push:
    branches:
      - main
      - v3

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Build
        run: npm run build
      - name: Upload build for re-use
        uses: actions/upload-artifact@v7.0.1
        with:
          name: build
          path: dist/
          retention-days: 1
  check:
    name: ${{ matrix.what }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        what:
          - ci
          - formatting
          - json
          - licenses
          - lockfile
          - manifest
          - md
          - ts
          - types
          - yml
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install tooling
        uses: asdf-vm/actions/install@v4.0.1
        if: ${{ matrix.what == 'ci' || matrix.what == 'sh' }}
      - name: Install dependencies
        run: npm clean-install
      - name: Check
        run: npm run "check:${WHAT}"
        env:
          WHAT: ${{ matrix.what }}
  codeql:
    name: CodeQL (${{ matrix.what }})
    runs-on: ubuntu-24.04
    needs:
      - build
    permissions:
      security-events: write # To upload CodeQL results
    strategy:
      fail-fast: false
      matrix:
        what:
          - actions
          - javascript
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4.37.3
        with:
          config-file: ./.github/codeql.yml
          languages: ${{ matrix.what }}
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v4.37.3
  gha-release:
    name: GitHub Actions Release Immutability
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'pull_request' && startsWith(github.event.pull_request.head.ref || github.ref_name, 'dependabot/github_actions/') }}
    permissions:
      pull-requests: write # To comment on a Pull Request
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Parse
        id: parse
        shell: bash
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          REPO=$(echo "${TITLE}" | awk -F' ' '{print $2}')
          OLD=$(echo "${TITLE}" | awk -F' ' '{print $4}')
          NEW=$(echo "${TITLE}" | awk -F' ' '{print $6}')

          {
            echo "repo=$REPO"
            echo "new=$NEW"
            echo "old=$OLD"
          } >>"$GITHUB_OUTPUT"
      - name: Check
        id: check
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          NEW: ${{ steps.parse.outputs.new }}
          OLD: ${{ steps.parse.outputs.old }}
          REPO: ${{ steps.parse.outputs.repo }}
        run: |
          set -euo pipefail

          WAS_IMMUTABLE=$(gh release view "v${OLD}" --repo "${REPO}" --json isImmutable | jq .isImmutable)
          IS_IMMUTABLE=$(gh release view "v${NEW}" --repo "${REPO}" --json isImmutable | jq .isImmutable)

          echo "::debug::was ${WAS_IMMUTABLE}; is ${IS_IMMUTABLE}"
          {
          case "${WAS_IMMUTABLE};${IS_IMMUTABLE}" in
          'true;true')
            echo "comment="
            ;;
          'false;false')
            echo "comment=${OLD} was not an immutable release and ${NEW} still is not. :neutral_face:"
            ;;
          'true;false')
            echo "comment=${OLD} was an immutable release but ${NEW} is not. :cry:"
            ;;
          'false;true')
            echo "comment=${OLD} was not an immutable release but ${NEW} is! :smile:"
            ;;
          esac
          } >>"$GITHUB_OUTPUT"
      - name: Comment
        if: ${{ steps.check.outputs.comment != '' }}
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
          GH_URL: ${{ github.server_url }}
          COMMENT: ${{ steps.check.outputs.comment }}
          NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
        run: |
          URL="${GH_URL}/${REPO}/pull/${NUMBER}"
          gh pr comment "${URL}" --body "${COMMENT}"
  odgen:
    name: ODGen
    runs-on: ubuntu-24.04
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Perform ODGen analysis
        uses: ericcornelissen/odgen-action@v1.1.1
        with:
          vulnerability_type: os_command, code_exec, proto_pollution, ipt, path_traversal
  reproducible:
    name: Reproducible build
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Simulate publish
        run: |
          npm run build
          npm pack
      - name: Compute checksum
        run: shasum -- *.tgz | tee checksums.txt
      - name: Reset to a clean state
        run: |
          npm run clean
          rm -- *.tgz
      - name: Simulate publish again
        run: |
          npm run build
          npm pack
      - name: Verify checksum
        run: shasum --check checksums.txt --strict
  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep:1.162.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Perform Semgrep analysis
        run: semgrep --sarif --output semgrep.sarif
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@f205ea1c3313d32999d8d6a48b4f6530d4437b38 # v4.37.4
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
  test:
    name: Test
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm clean-install
      - name: Run tests with coverage
        run: npm run coverage
  test-compat:
    name: Compatibility tests
    runs-on: ubuntu-24.04
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.0.0
          - 20.0.0
          - 20.19.0
          - 22.0.0
          - 22.13.0
          - 24.0.0
          - 26.0.0
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install compatible npm version
        run: npm install --global npm@8.1.2
      - name: Install dependencies
        run: npm clean-install
      - name: Download build
        uses: actions/download-artifact@v8.0.0
        with:
          name: build
          path: dist/
      - name: Run compatibility tests
        run: npm run test:compat
  test-mutation:
    name: Mutation tests
    runs-on: ubuntu-24.04
    needs:
      - test
    steps:
      - name: Verify action checksums
        uses: $/.github/actions/ghasum
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@v7.0.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Cache Stryker incremental report
        uses: actions/cache@v6.0.0
        with:
          path: .cache/stryker-incremental.json
          key: mutation-${{ github.run_number }}
          restore-keys: |
            mutation-
      - name: Install dependencies
        run: npm clean-install
      - name: Run mutation tests
        run: npm run mutation
