name: Rekor log monitor
on:
  workflow_dispatch:
    inputs:
      which:
        description: Which monitor
        required: true
        type: choice
        options:
          - new
          - old
  schedule:
    - cron: "0 * * * *"
    - cron: "30 * * * *"

permissions: read-all

jobs:
  run_consistency_proof_new:
    name: new
    if: inputs.which == 'new' || github.event.schedule == '0 * * * *'
    permissions:
      contents: read # Needed to checkout repositories
      issues: write # Needed if you set "file_issue: true"
    uses: ericcornelissen/rekor-monitor/.github/workflows/reusable_monitoring.yml@af347a2bff40e7cd8b28d8cc41a8161b5eb4c5bf
    with:
      file_issue: true # Strongly recommended: Files an issue on monitoring failure
      artifact_retention_days: 14 # Optional, default is 14: Must be longer than the cron job frequency
  run_consistency_proof_old:
    name: old
    if: inputs.which == 'old' || github.event.schedule == '30 * * * *'
    permissions:
      contents: read # Needed to checkout repositories
      issues: write # Needed if you set "file_issue: true"
      id-token: write # Needed to detect the current reusable repository and ref
    uses: sigstore/rekor-monitor/.github/workflows/reusable_monitoring.yml@main
    with:
      file_issue: true # Strongly recommended: Files an issue on monitoring failure
      artifact_retention_days: 14 # Optional, default is 14: Must be longer than the cron job frequency
